name: dart_example
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  csv: ^5.1.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
